name: Updated Page Sample

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
      pages: write
      id-token: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      
       

      - name: Add Artifact to publish
        run: |
         cd cucumber-reports/.
          
         
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
         name: Cucumber Reports
         path: ./cucumber-reports
         
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
          name: github-pages
          url: ${{steps.deployment.outputs.page_url}}

    steps:
          - uses: actions/download-artifact@main
            with:
             name: Cucumber Reports
             path: ./cucumber-reports
          - uses: actions/configure-pages@v1
          - uses: actions/upload-pages-artifact@v1
            with:
             path: ./cucumber-reports
          - id: deployment
            uses: actions/deploy-pages@main
